# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
stages:
  - build-doc
  - name: deploy-doc
    if: branch = master 
jobs:
  include:
    - stage: build-doc
      julia: 1.2
      script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip
    - stage: deploy-doc
      julia: 1.2
      before_script: julia --project=docs -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      provider: pages
      local_dir: docs/build
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      keep_history: true
