# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
julia:
  - 1.2
  - nightly
os:
  - linux
  - osx
  - windows
arch:
  - x64
  - x86
branches: # Save CI time by restricting CI to PRs and releases
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags for Documenter
    - /^release-.*$/ # Release branches, if any.
jobs:
  fast_finish: true
  allow_failures:
    - julia: nightly
  exclude:
    - arch: x86
      os: osx
  include:
    - stage: Documentation
      julia: 1.2
      script: julia --project=docs -e '
        using Pkg;
        Pkg.develop(PackageSpec(; path=pwd()));
        Pkg.instantiate();
        include("docs/make.jl");'
      after_success: skip
after_success:
  - julia -e '
      using Pkg;
      Pkg.add("Coverage");
      using Coverage;
      Codecov.submit(process_folder());'
